---
title: "Manufacturing_net_HT"
author: "Haleigh Tomlin"
date: "7/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(network)
library(igraph)
```


```{r}
man1 <- read_xlsx("Manufacturing.xlsx")
man2 <- read_xlsx("Manufacturing_2.xlsx")
```


```{r}
man1 <- man1 %>% mutate(Code = substr(ONETSOC, start = 1, stop = 7))
man2 <- man2 %>% mutate(Code2 = substr(Code, start = 1, stop = 7))
```

```{r}
table(man1$ONETSOC[man1$Type...1 == "STEM"])
table(man2$Code[man2$Type == "STEM"])
```

```{r}
man1 <- man1 %>% select(ONETSOC, CertName = `Certification Name`)
man2 <- man2 %>% select(ONETSOC = Code, cluster = `Career Cluster`,pathway = `Career Pathway`, Occupation, Type)
```

```{r}
manufacturing <- man2 %>% left_join(man1, by = "ONETSOC")
```

```{r}
manufacturing
```

```{r}
manufacturing <- manufacturing %>% mutate(ONETSOC = substr(ONETSOC, start = 1, stop = 7))
```


```{r}
stw_man_certs <- d %>% select(SOC, Cert = Certification.Name)
```

```{r}
table(manufacturing$ONETSOC[manufacturing$Type == "STW"] %in% stw_man_certs$SOC)
```

```{r}
manufacturing1 <- manufacturing %>% left_join(stw_man_certs, by = c("ONETSOC" = "SOC"))
```

```{r}
manufacturing1[manufacturing1$Type == "STEM",]
```

```{r}
manufacturing2 <- manufacturing1 %>% mutate(Certification = ifelse(is.na(CertName), Cert, CertName))
```

```{r}
manufacturing2
```

```{r}
m <- manufacturing2 %>% select(ONETSOC, Certification, Occupation, Type) %>% na.omit(ONETSOC, Certification)
```


```{r}
m[m$ONETSOC == "17-3029",]
```



```{r}
m_attributes1 <- m %>% select(name = ONETSOC, Occupation, Type)
m_attributes2 <- m %>% select(name = Certification, Occupation, Type)

m_attributes1 <- m_attributes1[!duplicated(m_attributes1$name),]
m_attributes2 <- m_attributes2[!duplicated(m_attributes2$name),]

m_attributes <- rbind(m_attributes1, m_attributes2)
```

```{r}
m
```

```{r}
m <- m %>% mutate(Occupation = gsub(" ", "\n", Occupation))
m_attributes <- m_attributes %>% mutate(Occupation = gsub(" ", "\n", Occupation))
```

```{r}
m <- m[!duplicated(m),]
```

```{r}
m[m$Occupation == "Electro-Mechanical\nand\nMechatronics\nTechnologists\nand\nTechnicians",]
```


```{r}
manu_net <- graph.data.frame(m, directed = F, vertices = m_attributes)
V(manu_net)$type <- bipartite.mapping(manu_net)$type
```


```{r, fig.height = 20, fig.width= 20}
plot(manu_net,
     vertex.shape = ifelse(V(manu_net)$type, "circle", "square"),
     vertex.color = ifelse(V(manu_net)$type == F, ifelse(V(manu_net)$Type == "STW", cbPalette[5], cbPalette[1]), cbPalette[4]),
     vertex.size = ifelse(V(manu_net)$type, 3, 9),
     vertex.label = ifelse(V(manu_net)$type == F, V(manu_net)$Occupation, NA),
     vertex.label.color = "black",
     vertex.label.cex = 0.6,
     edge.color = cbPalette.blk[1],
     edge.width = 1.5,
     layout = layout_nicely)
title(main = "Manufacturing Credential and Occupation Network", sub = "data from O*Net OnLine")
legend("bottomleft", legend = c("STW", "Non-STW"), col = c(cbPalette[5],cbPalette[1]), pch = 19, pt.cex = 1.5, bty = "n", title = "Type of Occupation", xjust = 0)
legend("bottomleft", legend = c("Credential", "Occupation"), pch = c(19, 15), pt.cex = 1.5, bty = "n", title = "Node Type", inset = c(0, .05), xjust = 0)
```

```{r}
get_network_stats(manu_net)
```


```{r}
library(ggraph)
```

```{r}
#Color Blind Palettes

#color blind palette with grey

cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

#color blind palette with black

cbPalette.blk<-c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

#display the palette

wheel <- function(col, radius = 1, ...)

  pie(rep(1, length(col)), col = col, radius = radius, ...)

wheel(cbPalette)
wheel(cbPalette.blk)
```



```{r, fig.height = 30}
ggraph(manu_net, layout = "kk")+ 
    geom_edge_link() + 
    geom_node_point(size = ifelse(V(manu_net)$type == F, 35, 8), colour = ifelse(V(manu_net)$type == F, ifelse(V(manu_net)$Type == "STW", cbPalette[2], cbPalette[4]), cbPalette[6])) +
  geom_node_text(aes(label = ifelse(V(manu_net)$type, NA, V(manu_net)$Occupation), repel = T, parse = T), show.legend = T) + theme_minimal() 
```

